### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies

### ISSUE THREAD

**Issue by marcianobandeira** [QuestPDF/library#15]
When I run project in Linux/Ubuntu, I have this exception: System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies.

On Mac and Windows, works.

Thanks

**Comment by MarcinZiabek** [comment]
Hello, This exception is directly connected to the SkiaSharp dependency. Can you please post your question in their repository, I bet they are more knowledgeable in this regard: https://github.com/mono/SkiaSharp

But first, please take a look at a couple of existing issues already created and answered: https://github.com/mono/SkiaSharp/issues/834

**Comment by marcianobandeira** [comment]
Thanks @MarcinZiabek this resolve my problem
https://github.com/mono/SkiaSharp/issues/834#issuecomment-504813021
