### ISSUE TITLE
Continuous Page / Bobine

### ISSUE THREAD

**Issue by marcianobandeira** [QuestPDF/library#16]
is it possible to generate a continuous page, for to print in bobine paper?

I see wich is possible to informe PageSize, but, how to calculate the total height for to generate single page?

thanks.

Sorry for my bad english :)

**Comment by MarcinZiabek** [comment]
Hello,

I am currently working on a change that allows using multiple page sizes within a single document. This change should make your request possible. 

Can you estimate how long your content will be in terms of physical size? For example A4 page width, 10 meters long max.

**Comment by marcianobandeira** [comment]
Hello @MarcinZiabek thanks for your return. I want to print in bobine paper with 80mm of width. The height don't have a predefined size, but, I believe that at the most one meter.

I'm following the project around here, congratulations on it.

**Comment by marcianobandeira** [comment]
here's an example, it's a simple page, which grows with its content.
[NF Bobina.pdf](https://github.com/QuestPDF/library/files/6851534/NF.Bobina.pdf)

**Comment by MarcinZiabek** [comment]
That's great :) For technical reasons, I need to put a constraint that describes the maximum page size. For now, I decided to go with 100 000 points, which is around 35 meters. It should be plenty for most use cases.

**Comment by MarcinZiabek** [comment]
This is my plan for the current API design (a minor breaking change 😥). You may find that within a single document, you can define multiple sections of different page size and margins:

```c#
container
    .Page(page =>
    {
        page.MarginVertical(40);
        page.MarginHorizontal(50);
        
        page.Size(PageSizes.A4);
            
        page.Header().Element(ComposeHeader);
        page.Content().Element(ComposeContent);
        page.Footer().AlignCenter().PageNumber("Page A {number}");
    })
    .Page(page =>
    {
        page.MarginVertical(80);
        page.MarginHorizontal(100);
        
        page.Size(PageSizes.A3);
            
        page.Header().Element(ComposeHeader);
        page.Content().Element(ComposeContent2);
        page.Footer().AlignCenter().PageNumber("Page B {number}");
    });
```

**Comment by MarcinZiabek** [comment]
So the plan is to give the possibility to define additional size constraints, e.g. minimum and maximum size that the content will fit as best as it can. For example: MinSize() and MaxSize() or something...

**Comment by MarcinZiabek** [comment]
@marcianobandeira This functionality is available within the QuestPDF 2021.08 release. 

Please refer to the documentation section about continuous page sizes: https://www.questpdf.com/documentation/patterns-and-practices.html#continuous-page-size

**Comment by marcianobandeira** [comment]
Hello @MarcinZiabek, sorry for my long delay to reply. 
I had a lot of work in the last few weeks.
It's fantastic, I will to do tests and reply here.
Thank you very much.

**Comment by MarcinZiabek** [comment]
Hi @marcianobandeira I would like to ask you if this functionality works for you? I am hoping to close this issue :)

**Comment by marcianobandeira** [comment]
Hi @MarcinZiabek 

I updated from nuget, and tested with this code:


`
public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.MarginHorizontal(5);
                page.MarginVertical(5);
                page.ContinuousSize(150);
                page.Header().Text("Header");
                page.Content().Stack(stack =>
                {
                    for (var i = 0; i < 300; i++)
                        stack.Item().AlignCenter().Text($"Test {i}");
                });
                page.Footer().Text("Footer");
            });
        }
`

Have a little problem, he generated a blank space before footer.. 
[Teste.pdf](https://github.com/QuestPDF/library/files/7092846/Teste.pdf)

**Comment by MarcinZiabek** [comment]
@marcianobandeira I am very sorry to hear that. Apparently, I have broken this functionality when simplifying the code :( 

**I have just published a new update that should fix this problem. Please test QuestPDF 2021.9.2 and let me know if it works for you.**

**Comment by marcianobandeira** [comment]
@MarcinZiabek its works perfectly.
Thank you very mutch. Congratulations for your project, he is very best.
[Teste Novo.pdf](https://github.com/QuestPDF/library/files/7093799/Teste.Novo.pdf)
