### ISSUE TITLE
Is there any plan to add Acroforms functions to this library?

### ISSUE THREAD

**Issue by Pilchard123** [QuestPDF/library#2]
The title, really. I don't know how hard it would be to do, but it would be really useful to have the ability to add editable fields to a generated PDF. I would also suggest XFA, but I believe that needs a licence from Adobe.

**Comment by MarcinZiabek** [comment]
Right now, the library consists mostly of the layouting algorithm and sophisticated fluent API implementation. The actual PDF rendering happens in SkiaSharp, a rendering engine used in Chrome, Xamarin and Flutter. This library provides some additional, PDF-specific functionalities, such as annotations and links. However, it is purely (as far as I know) read-only.

Technically, SkiaSharp is, in the vast majority, strongly decoupled from the layouting engine and can be replaced by another implementation injected via the proper interface. Then, new components can detect such a special type of implementation and describe the content, including any kind of forms or XFA.

**Taking into account that writing a PDF generator is hard and timeconsuming, I expect that QuestPDF will strongly rely on SkiaSharp, a very mature and stable dependency, and therefore it is very unlikely that requested features will be available in the future.**

Please take a look at the roadmap to find a general idea of which features are currently considered: https://www.questpdf.com/documentation/releases.html#roadmap
