### ISSUE TITLE
Bug on Resize Image

### ISSUE THREAD

**Issue by marcianobandeira** [QuestPDF/library#22]
Hello,

I'm testing this library with images, but, in the somethimes cases, ocurrs crash in PdfCanvas.cs, at point: Canvas.Dispose()

        public override void EndDocument()
        {
            Canvas.Dispose();  <-- Canvas is null

            Document.Close();
            Document.Dispose();
        }

I build a little project for the simulate bug.
[testpdf.zip](https://github.com/QuestPDF/library/files/7138356/testpdf.zip)

Thanks

**Comment by MarcinZiabek** [comment]
Hi, thank you for letting me know about this issue. I have analyzed your submission and indeed, there is a bug.

So far, I think that the resize image functionality works correctly. Making the long story short, the "FitHeight" takes into account only available height when calculating the final image size, preserving its aspect ratio. As a result, when image is scaled to fit available height, it may require more width space that is available. In such case, the component will try to render itself on the next page, and the next... until there is enough space.

In yours case, the height is set to 200 pixels, the image has size is 155x57 pixels, so required width is 200/57*155 = 543 pixels. You have also used constant row->column width 200 pixels, which is not enough. In your case, way better option would be to use FitArea option.

So the library should throw the InfiniteLayoutException in this case, as the image will never have enough space. You have found a very special corner case when such situation happens on the first page / the result is not wrapped in any other continouos container. 

I will do the fix as soon as possible. Recently I have also started some effort to help developers understand the InfiniteLayoutException and provide tools to find problematic components. You may find the progress in the "element-proxy" branch.

**Comment by MarcinZiabek** [comment]
@marcianobandeira Hi, I have deployed an update that properly throws a LayoutOverflow exception in cases you have experienced. In the future, I will make yet another update to help developers understand the root cause and help with fixing the issue. Can you please confirm that the library works properly now? :)

**Comment by marcianobandeira** [comment]
hello @MarcinZiabek 

Perfect, I tested and the library is ok.

Thank you very much.
