### ISSUE TITLE
strikethrough textstyle

### ISSUE THREAD

**Issue by lujianjun19** [QuestPDF/library#24]
Can the library provide strikethrough text style.

![image](https://user-images.githubusercontent.com/56019342/133215179-c44767d7-7c54-42ca-88d5-c75778f10da7.png)

**Comment by MarcinZiabek** [comment]
Hello, Please make a try with the new release: QuestPDF 2021.10-beta2 and let me know if it works for you :)

```csharp
TextStyle.Default.Strikethrough()
```

**Comment by lujianjun19** [comment]
Hello Marcin,

the strikethroght style works well. But QuestPDF 2021.10-beta2 has a bug. The table is cross two page. the table will have a empty row at end of page.

![image](https://user-images.githubusercontent.com/56019342/133370748-e65c39c5-05e6-42a6-b733-77648888ee17.png)

**Comment by lujianjun19** [comment]
here is my code
public class TableComponent : IComponent
    {
        private readonly IEnumerable<ItemModel> _items;
        public TableComponent(List<ItemModel> items)
        {
            _items = items;
        }
        public void Compose(IContainer container)
        {
            container.PaddingTop(5).Decoration(decoration =>
            {
                decoration.Header().Border(0.75f).Background("CCC").Row(row =>
                {
                    row.ConstantColumn(25).Border(0.75f).Padding(2f).Text("No.");
                    row.RelativeColumn().Border(0.75f).Padding(2f).Text("Equipment");
                    row.RelativeColumn().Border(0.75f).Padding(2f).Text("Location");
                    row.RelativeColumn().Border(0.75f).Padding(2f).Text("Quantity");
                    row.RelativeColumn().Border(0.75f).Padding(2f).Text("Material");
                    row.ConstantColumn(40).Border(0.75f).Padding(2f).Text("Mass");
                    row.ConstantColumn(25).Border(0.75f).Padding(2f).Text("Unit");
                    row.RelativeColumn().Border(0.75f).Padding(2f).Text("Where");
                    row.RelativeColumn().Border(0.75f).Padding(2f).Text("Remarks");                    
                });

                if (_items.Any())
                {
                    decoration
                        .Content()
                        .Stack(column =>
                        {
                            var i = 0;

                            foreach (var item in _items)
                            {
                                column.Item().Border(0.75f).Row(row =>
                                {
                                    row.ConstantColumn(25).Border(0.75f).Padding(2f).Text($"{++i}", TextStyle.Default.Size(9));
                                    row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.EquipmentName, TextStyle.Default.Size(9));
                                    row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.Location, TextStyle.Default.Size(9));
                                    row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.Quantity, TextStyle.Default.Size(9));
                                    row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.Material, TextStyle.Default.Size(9));
                                    row.ConstantColumn(40).Border(0.75f).Padding(2f).Text(item.Mass, TextStyle.Default.Size(9));
                                    row.ConstantColumn(25).Border(0.75f).Padding(2f).Text(item.Unit, TextStyle.Default.Size(9));
                                    row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.WhereUsed, TextStyle.Default.Size(9));
                                    row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.Remarks, TextStyle.Default.Size(9).Strikethrough());

                                });
                            }
                        });
                }
            });
        }
    }

//here is table code

**Comment by lujianjun19** [comment]
It casued by this sentence. container.PaddingTop(5).Decoration(decoration =>
I removed PaddingTop(5). the empty row will disappear.

**Comment by MarcinZiabek** [comment]
Hi, it is not technically a bug but something that most developers will not expect. I need to make sure to provide good documentation for this case. Basically, this issue is a result of the text being pageable by default now (whereas the old version of the library doesn't support text paging).

The simplest fix in your case is to make sure that table rows are not paged and always wrapped to the next page where there is not space enough, like so:

```csharp
decoration
    .Content()
    .Stack(column =>
    {
        var i = 0;

        foreach (var item in _items)
        {
            column.Item().ShowEntire().Border(0.75f).Row(row =>   // here is a change
            {
                row.ConstantColumn(25).Border(0.75f).Padding(2f).Text($"{++i}", TextStyle.Default.Size(9));
                row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.EquipmentName, TextStyle.Default.Size(9));
                row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.Location, TextStyle.Default.Size(9));
                row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.Quantity, TextStyle.Default.Size(9));
                row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.Material, TextStyle.Default.Size(9));
                row.ConstantColumn(40).Border(0.75f).Padding(2f).Text(item.Mass, TextStyle.Default.Size(9));
                row.ConstantColumn(25).Border(0.75f).Padding(2f).Text(item.Unit, TextStyle.Default.Size(9));
                row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.WhereUsed, TextStyle.Default.Size(9));
                row.RelativeColumn().Border(0.75f).Padding(2f).Text(item.Remarks, TextStyle.Default.Size(9).Strikethrough());

            });
        }
    });
```

Notice usage of this component: https://www.questpdf.com/documentation/api-reference.html#show-entire

**Comment by lujianjun19** [comment]
Thanks for your quick response. The issue fixed. It works. :-)
